N = 4
s = 1
t = 4
Tmax = 6

# lista łuków: (i,j,c,t)
arcs = [
    { i = 1, j = 2, c = 0.5, t = 5 },   # s->a
    { i = 2, j = 4, c = 0.5, t = 5 },   # a->t
    { i = 1, j = 3, c = 5.0, t = 1 },   # s->b
    { i = 3, j = 4, c = 5.0, t = 1 }    # b->t
]
