m = 10
n = 12
k = 2

# Kontenery: [wiersz, kolumna]
containers = [
  [1, 2],  [1, 5],  [1, 9],
  [2, 1],  [2, 4],  [2, 7],  [2, 11],
  [3, 3],  [3, 6],  [3, 10],
  [4, 2],  [4, 5],  [4, 8],  [4, 12],
  [5, 1],  [5, 4],  [5, 7],  [5, 9],
  [6, 3],  [6, 6],  [6, 10],
  [7, 2],  [7, 5],  [7, 8],  [7, 11],
  [8, 1],  [8, 4],  [8, 7],  [8, 12],
  [9, 3],  [9, 6],  [9, 9],
  [10, 2], [10, 5], [10, 8], [10, 10], [10, 12],
  [5, 11], [6, 12], [9, 11]
]

